# Generated by Django 3.2 on 2022-06-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('block', models.CharField(blank=True, max_length=20, null=True)),
                ('flat_id', models.CharField(blank=True, max_length=20, null=True)),
                ('apartment_type', models.CharField(choices=[('S', 'Shared Apartment'), ('X', 'Exclusive Apartment')], default=0, max_length=20)),
                ('bedroom_type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('apartment_image', models.ImageField(null=True, upload_to='apartment/')),
            ],
            options={
                'ordering': ('flat_id',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citys', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='city')),
                ('status', models.CharField(default=0, editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(help_text='enter a valid apartment name', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, default='download_6mOeWlD.jfif', null=True, upload_to='uploads/post_photos')),
                ('city', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Estates',
                'ordering': ('estate_name',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name_rooms', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('blocks', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('flat_id_rooms', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('apartment_type', models.CharField(choices=[('S', 'Shared Apartment'), ('X', 'Exclusive Apartment')], default=0, editable=False, max_length=20)),
                ('bedroom_type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('room_id', models.CharField(blank=True, max_length=20, null=True)),
                ('room_types', models.CharField(choices=[('Executives', 'executives'), ('Standard', 'standard'), ('Mini', 'mini'), ('Deluxe', 'deluxe')], max_length=15, unique=True)),
                ('capacity', models.SmallIntegerField(default=0)),
                ('ammenities', models.TextField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='uploads/post_photos')),
                ('unique_room_id', models.CharField(blank=True, max_length=20, null=True)),
                ('rent', models.FloatField()),
                ('service_charge', models.FloatField()),
                ('power_charge', models.FloatField()),
                ('price', models.FloatField(editable=False)),
                ('occupied', models.CharField(choices=[('available', 'available'), ('expired', 'expired'), ('terminated', 'terminated'), ('running', 'running')], default='available', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Room',
                'ordering': ('apartment_name_rooms',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testemonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='testemonials')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_no', models.CharField(max_length=2)),
                ('total_flat', models.CharField(max_length=10, null=True)),
                ('estate_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.estate')),
            ],
        ),
    ]
