# Generated by Django 3.2 on 2022-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_alter_room_bedroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_types',
            field=models.CharField(choices=[('Executives', 'executives'), ('Standard', 'standard'), ('Mini', 'mini'), ('Deluxe', 'deluxe')], max_length=15),
        ),
    ]
